### ISSUE TITLE
How to use Github bot to comment

### ISSUE THREAD

**Issue by nmd2k** [quentinguidee/pep8-action#1]
Hi, firstly I really appreciate your work.

I saw you said in `README` that I can setup Github bot to comment on pep8 errors in PR. (Like the image below in `flake8` action)
![image](https://user-images.githubusercontent.com/48562727/141412294-208c4269-53cf-4b48-9449-d456182bcc46.png)

How can I do that?

**Comment by quentinguidee** [comment]
Hi! Thanks for your issue.

In fact, what I meant by "comment the PR" is that you can get the output of this bot and create a "normal" comment on the Pull Request with another bot like `actions/github-script` with something like this :
```js
github.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: message,
})
```
(example here: https://github.com/Omega-Numworks/Omega-Robot/blob/53c3e058923d343cec548dcd15dd4d6bd00b1166/.github/workflows/pep8.yml#L18-L38)

That said, while there must be a way to use a similar system for commenting directly in a code review, it would be a great idea to integrate it directly into the current bot. I'll take a closer look at this this weekend. Thanks!

**Comment by nmd2k** [comment]
Thanks @quentinguidee, a really detailed guide from you.

**Comment by quentinguidee** [comment]
I found the time to take care of it today. I opened a PR (#2). Everything should work, I'm testing it tonight then if it's ready I'll post it tonight or tomorrow.

**Comment by quentinguidee** [comment]
I managed to get some things working.

![image](https://user-images.githubusercontent.com/12123721/141662409-5eaef620-0511-4345-8782-747792ecbe8e.png)

A little harder than I though (edge cases to manage…). I think I'll get a working beta tomorrow.

**Comment by nmd2k** [comment]
Your work looks amazing. I'm looking forward to seeing the final release 🚀

**Comment by quentinguidee** [comment]
Thanks! 😄

If you need it now, I think you can already try the dev version with something like this :

`.github/workflows/tests.yml`
```yml
name: Tests

on: [pull_request_target]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: PEP8 Action
      uses: quentinguidee/pep8-action@v2.0.13-dev
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
```

The only thing I have to finish is to delete/hide previous review. In fact, the GitHub API allows to delete a review… only if the review is not submitted :/ So, the delete call will throw a 404 error, but the review should work correctly. Don't hesitate to say if you encounter any bugs/problems/ideas.
